motd=\u00a76Cobblemon \u00a72Harcadia Academy
server-port=25512
online-mode=true
white-list=true
enforce-whitelist=true
enable-rcon=false
view-distance=8
simulation-distance=6
max-players=20
spawn-protection=0
