<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>CobblemonHarcadiaAcademy</AssemblyName>
    <RootNamespace>HarcadiaLauncher</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.2.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="launcher.config.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="modpack.manifest.example.json" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="Assets\logo.svg" />
    <Resource Include="Assets\harcadia-background.png" />
    <Resource Include="Assets\discord-pokeball.jpg" />
    <Resource Include="Assets\boutique-logo.png" />
  </ItemGroup>
</Project>
